name: regional_infrastructure_resilience_auditor
version: 1.0.0
config-version: 2

profile: regional_infrastructure_resilience_auditor

model-paths: ["models"]
seed-paths: ["seeds"]
snapshot-paths: ["snapshots"]
macro-paths: ["macros"]
test-paths: ["tests"]

target-path: target
clean-targets:
  - target
  - dbt_packages

models:
  regional_infrastructure_resilience_auditor:
    +materialized: view
    staging:
      +schema: staging
    intermediate:
      +schema: intermediate
    dimensions:
      +schema: dimensions
    facts:
      +schema: facts
    marts:
      +schema: marts
